// Mock data for Quant Lab: strategies, leaderboard, push feed.

function seededWalk(seed, n, drift, vol, start = 0) {
  let s = seed;
  const rand = () => {
    s = (s * 9301 + 49297) % 233280;
    return s / 233280;
  };
  const out = [];
  let v = start;
  for (let i = 0; i < n; i++) {
    v += drift + (rand() - 0.5) * vol;
    out.push(Number(v.toFixed(3)));
  }
  return out;
}

const MARKET_STRATEGIES = [
  {
    id: 'btc-macd-momentum',
    name: 'BTC MACD Momentum',
    symbol: 'BTC',
    market: 'Crypto',
    universe: { kind: 'single', label: 'BTC', detail: 'Bitcoin spot, 4h bars' },
    author: { name: 'Jack Simonson', org: 'aime Labs', avatarColor: '#0284c7' },
    blurb: 'Confirmed momentum bursts on 4h MACD. Lean directional, modest leverage.',
    tags: ['Trend', 'MACD', 'Crypto', 'Beginner'],
    metrics: { ret1Y: 84.2, sharpe1Y: 2.41, maxDD: -11.2, cagr5Y: 38.7, winRate: 62, trades: 184, followers: 2840 },
    curve: seededWalk(11, 120, 0.78, 1.6, 0),
    published: '2026-02-14',
    aiMatch: 92,
  },
  {
    id: 'eth-mean-reversion',
    name: 'ETH Mean Reversion',
    symbol: 'ETH',
    market: 'Crypto',
    universe: { kind: 'single', label: 'ETH', detail: 'Ethereum spot, 1h bars' },
    author: { name: 'Louis Szeto', org: 'Louis Szeto Quant', avatarColor: '#7c3aed' },
    blurb: 'Buy oversold dips, fade exhaustion rallies. High win-rate, modest size.',
    tags: ['Mean reversion', 'RSI', 'Crypto'],
    metrics: { ret1Y: 41.8, sharpe1Y: 2.27, maxDD: -7.5, cagr5Y: 24.3, winRate: 71, trades: 312, followers: 1290 },
    curve: seededWalk(7, 120, 0.34, 0.72, 0),
    published: '2025-11-04',
    aiMatch: 86,
  },
  {
    id: 'sol-breakout',
    name: 'SOL Breakout Pro',
    symbol: 'SOL',
    market: 'Crypto',
    universe: { kind: 'single', label: 'SOL', detail: 'Solana spot, daily bars' },
    author: { name: 'McCartney Taylor', org: 'McCartney Taylor', avatarColor: '#06b6d4' },
    blurb: 'Catch 3-day range breaks with volume confirm. Few trades, fat tails.',
    tags: ['Breakout', 'Volume', 'High variance'],
    metrics: { ret1Y: 131.99, sharpe1Y: 1.55, maxDD: -28.4, cagr5Y: 47.6, winRate: 55, trades: 64, followers: 902 },
    curve: seededWalk(23, 120, 1.05, 2.8, 0),
    published: '2026-01-31',
    aiMatch: 74,
  },
  {
    id: 'qqq-rotation',
    name: 'High-Conviction Mega-Cap Rotation',
    symbol: 'QQQ',
    market: 'US Equity',
    universe: { kind: 'multi', label: 'Auto-picks from QQQ 100', detail: 'Weekly rotation, holds 5 names at a time' },
    author: { name: 'Zheng Tian', org: 'Financial Freedom', avatarColor: '#0ea5e9' },
    blurb: 'Weekly rotation across QQQ constituents on momentum & earnings drift.',
    tags: ['Rotation', 'Equity', 'Weekly'],
    metrics: { ret1Y: 29.02, sharpe1Y: 2.39, maxDD: -14.4, cagr5Y: 22.1, winRate: 66, trades: 96, followers: 412 },
    curve: seededWalk(31, 120, 0.28, 0.58, 0),
    published: '2026-01-18',
    aiMatch: 81,
  },
  {
    id: 'pca-residual',
    name: 'PCA Residual Mean Reversion',
    symbol: 'US Equity',
    market: 'US Equity',
    universe: { kind: 'multi', label: 'Auto-picks from S&P 500', detail: 'Stat-arb, holds 6–12 paired longs/shorts' },
    author: { name: 'Daniel Chen', org: 'Daniel Chen', avatarColor: '#10b981' },
    blurb: 'Stat-arb on PCA residuals across S&P sectors. Beta-neutral.',
    tags: ['Stat-arb', 'Market-neutral', 'Equity'],
    metrics: { ret1Y: 18.4, sharpe1Y: 3.28, maxDD: -4.2, cagr5Y: 14.1, winRate: 73, trades: 540, followers: 142 },
    curve: seededWalk(41, 120, 0.18, 0.22, 0),
    published: '2026-04-22',
    aiMatch: 78,
  },
  {
    id: 'leveraged-etf',
    name: 'Leveraged ETF Momentum Allocator',
    symbol: 'TQQQ',
    market: 'US Equity',
    universe: { kind: 'multi', label: 'Rotates: TQQQ / SOXL / SPXL', detail: 'Regime-gated, holds 1 leveraged ETF' },
    author: { name: 'Martin Mathew', org: 'Martin Mathew', avatarColor: '#ef4444' },
    blurb: 'Regime-aware leverage across TQQQ / SOXL / SPXL. Risk-on-only.',
    tags: ['Leverage', 'Regime', 'Aggressive'],
    metrics: { ret1Y: 116.93, sharpe1Y: 2.18, maxDD: -31.7, cagr5Y: 52.4, winRate: 58, trades: 78, followers: 1820 },
    curve: seededWalk(53, 120, 0.94, 2.4, 0),
    published: '2026-03-08',
    aiMatch: 69,
  },
  {
    id: 'omni-paradox',
    name: 'TheOmniscientParadox',
    symbol: 'SPY',
    market: 'US Equity',
    universe: { kind: 'single', label: 'SPY', detail: 'S&P 500 ETF, daily bars' },
    author: { name: 'Naitik Gupta', org: 'Desenyon Trade Club', avatarColor: '#8b5cf6' },
    blurb: 'Meta-strategy that votes across 7 sub-signals. Conservative ensemble.',
    tags: ['Ensemble', 'Equity', 'Voting'],
    metrics: { ret1Y: 49.37, sharpe1Y: 3.97, maxDD: -8.8, cagr5Y: 28.9, winRate: 68, trades: 220, followers: 1180 },
    curve: seededWalk(67, 120, 0.42, 0.46, 0),
    published: '2026-01-31',
    aiMatch: 88,
  },
  {
    id: 'kinetic-titan',
    name: 'The Kinetic Titan',
    symbol: 'NQ',
    market: 'US Equity',
    universe: { kind: 'single', label: 'NQ futures', detail: 'Nasdaq-100 e-mini, 5m bars' },
    author: { name: 'Naitik Gupta', org: 'Desenyon Trade Club', avatarColor: '#8b5cf6' },
    blurb: 'Intraday NQ futures momentum with adaptive stops.',
    tags: ['Intraday', 'Futures', 'Momentum'],
    metrics: { ret1Y: 43.85, sharpe1Y: 2.41, maxDD: -16.3, cagr5Y: 30.3, winRate: 59, trades: 412, followers: 214 },
    curve: seededWalk(79, 120, 0.36, 0.74, 0),
    published: '2026-04-30',
    aiMatch: 72,
  },
];

// Strategies the user has favorited ("On Watch").
// deployStatus:
//   'watching'  — default, AimeClaw only tracks signals (no money, no execution)
//   'paper'     — deployed to AInvest Paper account (simulated $)
//   'live'      — deployed to a connected broker account (real $)
//   'paused'    — user-paused or auto-paused (guardrail tripped)
const WATCHED_STRATEGIES = [
  {
    id: 'btc-macd-momentum',
    addedOn: '2026-04-18T09:30:15Z',
    runDays: 25,
    deployStatus: 'paper',
    deployAccount: { kind: 'paper', label: 'AInvest Paper', tail: '****0272' },
    capital: 10000,
    todayPnLPct: 1.84,
    todayPnL: 184.32,
    cumPnLPct: 6.12,
    cumPnL: 612.0,
    sharpe: 2.41,
    maxDD: -3.2,
    winRate: 62,
    trades: 18,
    lastSignal: { kind: 'buy', text: 'Bought BTC @ 67,420', at: '2h ago' },
    nextRun: 'in 14m',
    health: 'healthy',
    curve: seededWalk(11, 60, 0.42, 0.84, 0),
    positions: [
      { symbol: 'BTC',  qty: 0.158,  avg: 64200, last: 67420, mktValue: 10652.36, unreal: 508.76, pct: 5.02, side: 'long' },
    ],
  },
  {
    id: 'qqq-rotation',
    addedOn: '2026-04-22T14:05:42Z',
    runDays: 21,
    deployStatus: 'live',
    deployAccount: { kind: 'live', label: 'IBKR Margin', tail: '****0488' },
    capital: 25000,
    todayPnLPct: -0.42,
    todayPnL: -42.18,
    cumPnLPct: 3.18,
    cumPnL: 318.4,
    sharpe: 1.92,
    maxDD: -2.1,
    winRate: 66,
    trades: 12,
    lastSignal: { kind: 'rebalance', text: 'Rebalance window opens Mon 9:30 ET', at: 'pending' },
    nextRun: 'Mon 09:30',
    health: 'healthy',
    curve: seededWalk(31, 60, 0.18, 0.4, 0),
    positions: [
      { symbol: 'NVDA', qty: 18, avg: 142.10, last: 148.62, mktValue: 2675.16, unreal: 117.36, pct: 4.59, side: 'long' },
      { symbol: 'MSFT', qty: 6,  avg: 412.40, last: 421.05, mktValue: 2526.30, unreal: 51.90,  pct: 2.10, side: 'long' },
      { symbol: 'GOOG', qty: 14, avg: 178.20, last: 175.84, mktValue: 2461.76, unreal: -33.04, pct: -1.32, side: 'long' },
      { symbol: 'AVGO', qty: 12, avg: 198.60, last: 204.18, mktValue: 2450.16, unreal: 66.96,  pct: 2.81, side: 'long' },
      { symbol: 'AAPL', qty: 14, avg: 184.10, last: 182.04, mktValue: 2548.56, unreal: -28.84, pct: -1.12, side: 'long' },
    ],
  },
  {
    id: 'pca-residual',
    addedOn: '2026-05-02T08:12:33Z',
    runDays: 11,
    deployStatus: 'paper',
    deployAccount: { kind: 'paper', label: 'AInvest Paper', tail: '****0272' },
    capital: 5000,
    todayPnLPct: 0.21,
    todayPnL: 21.6,
    cumPnLPct: 0.92,
    cumPnL: 92.0,
    sharpe: 3.04,
    maxDD: -0.8,
    winRate: 71,
    trades: 64,
    lastSignal: { kind: 'sell', text: 'Closed 3 residual shorts', at: '38m ago' },
    nextRun: 'in 22m',
    health: 'healthy',
    curve: seededWalk(41, 60, 0.12, 0.18, 0),
    positions: [
      { symbol: 'NVDA', qty: 8,  avg: 145.30, last: 148.62, mktValue: 1188.96, unreal: 26.56,  pct: 2.29, side: 'long' },
      { symbol: 'XLK',  qty: 24, avg: 232.10, last: 234.62, mktValue: 5630.88, unreal: 60.48,  pct: 1.08, side: 'long' },
      { symbol: 'XLF',  qty: 38, avg: 48.20,  last: 47.84,  mktValue: 1817.92, unreal: -13.68, pct: -0.75, side: 'short' },
      { symbol: 'XLE',  qty: 22, avg: 96.40,  last: 95.12,  mktValue: 2092.64, unreal: -28.16, pct: -1.33, side: 'short' },
    ],
  },
  {
    id: 'eth-mean-reversion',
    addedOn: '2026-05-10T16:45:08Z',
    runDays: 3,
    deployStatus: 'watching',
    deployAccount: null,
    capital: 0,
    todayPnLPct: 0.62,
    todayPnL: 0,
    cumPnLPct: 1.84,
    cumPnL: 0,
    sharpe: 1.7,
    maxDD: -1.2,
    winRate: 68,
    trades: 6,
    lastSignal: { kind: 'buy', text: 'Signal: long ETH near 3,210 — deploy to act on it', at: '12m ago' },
    nextRun: 'in 31m',
    health: 'fresh',
    curve: seededWalk(17, 60, 0.24, 0.36, 0),
    positions: [],
  },
  {
    id: 'sol-breakout',
    addedOn: '2026-05-08T11:22:50Z',
    runDays: 5,
    deployStatus: 'paused',
    stoppedOn: '2026-05-13T14:22:00Z',
    deployAccount: { kind: 'paper', label: 'AInvest Paper', tail: '****0272' },
    capital: 10000,
    todayPnLPct: 0,
    todayPnL: 0,
    cumPnLPct: -2.41,
    cumPnL: -241.2,
    sharpe: 0.84,
    maxDD: -3.6,
    winRate: 40,
    trades: 4,
    lastSignal: { kind: 'alert', text: 'Drawdown breached -3% guardrail', at: 'yesterday' },
    nextRun: 'paused',
    health: 'warning',
    curve: seededWalk(23, 60, -0.18, 1.1, 0),
    positions: [],
  },
];

// Accounts the user can deploy to
const DEPLOY_TARGETS = [
  { id: 'paper', kind: 'paper', label: 'AInvest Paper', tail: '****0272', sub: 'Simulated $100,000 · no risk', cash: 100000, badge: 'Recommended' },
  { id: 'ibkr',  kind: 'live',  label: 'IBKR Margin',   tail: '****0488', sub: 'Real money · margin enabled', cash: 24812.43, badge: null },
  { id: 'alpaca', kind: 'live', label: 'Alpaca Live',   tail: '****6611', sub: 'Real money · equities + crypto', cash: 8420.10, badge: null },
  { id: 'hyperliquid', kind: 'live', provider: 'hyperliquid', label: 'Hyperliquid', tail: '0xA1B…F09e', sub: 'Real money · crypto perpetuals', cash: 5240.00, badge: null },
];

// AI push feed for On Watch
const PUSH_FEED = [
  {
    id: 'p1',
    at: '2m ago',
    kind: 'trade',
    source: 'deployed',
    strategyId: 'btc-macd-momentum',
    title: 'BTC MACD closed a winning long',
    body: 'BUY 0.158 BTC @ $64,200 → SELL @ $67,420. Realized +$508.76 (+2.84%).',
    cta: 'View',
  },
  {
    id: 'p2',
    at: '15m ago',
    kind: 'trade',
    source: 'deployed',
    strategyId: 'qqq-rotation',
    title: 'QQQ Rotation executed rebalance',
    body: 'Sold META 50 shares @ $512.30, Bought NVDA 25 shares @ $1,024.50. 4 orders filled.',
    cta: 'View',
  },
  {
    id: 'p3',
    at: '1h ago',
    kind: 'milestone',
    source: 'deployed',
    strategyId: 'btc-macd-momentum',
    title: 'Cumulative return reached +6%',
    body: 'BTC MACD Momentum cumulative return hit +6.12% after 25 days of live trading.',
    cta: 'View',
  },
  {
    id: 'p4',
    at: '2h ago',
    kind: 'trade',
    source: 'activity',
    strategyId: 'eth-mean-reversion',
    title: 'ETH Mean Reversion triggered a BUY signal',
    body: 'Signal: BUY 2.5 ETH @ $3,180. RSI dipped below 30 on 1h chart — mean-reversion entry.',
    cta: 'View',
  },
  {
    id: 'p5',
    at: '5h ago',
    kind: 'milestone',
    source: 'activity',
    strategyId: 'pca-residual',
    title: 'Cumulative return reached +3%',
    body: 'PCA Residual Mean Reversion hit +3.04% cumulative since added to Activity 11 days ago.',
    cta: 'View',
  },
  {
    id: 'p6',
    at: 'yesterday',
    kind: 'trade',
    source: 'deployed',
    strategyId: 'qqq-rotation',
    title: 'QQQ Rotation sold TSLA',
    body: 'SELL 30 shares TSLA @ $248.70. Position closed after rotation signal. Realized +$312.40.',
    cta: 'View',
  },
  {
    id: 'p7',
    at: 'yesterday',
    kind: 'milestone',
    source: 'activity',
    strategyId: 'sol-breakout',
    title: 'Cumulative return dropped below -2%',
    body: 'SOL Breakout Pro cumulative return fell to -2.41%. Drawdown reached -3.6% — near guardrail.',
    cta: 'View',
  },
];

// Leaderboard tickers for the QC-style chart
const LEADERBOARD_LINES = [
  { id: 'btc-macd-momentum', color: '#0284c7' },
  { id: 'eth-mean-reversion', color: '#7c3aed' },
  { id: 'sol-breakout', color: '#06b6d4' },
  { id: 'qqq-rotation', color: '#0ea5e9' },
  { id: 'pca-residual', color: '#10b981' },
  { id: 'leveraged-etf', color: '#ef4444' },
  { id: 'omni-paradox', color: '#8b5cf6' },
  { id: 'kinetic-titan', color: '#64748b' },
];

const ASSET_FILTERS = ['All', 'Crypto', 'US Equity', 'Futures', 'ETF'];
const STYLE_FILTERS = ['All styles', 'Trend', 'Mean reversion', 'Breakout', 'Stat-arb', 'Rotation', 'Ensemble', 'Intraday'];

Object.assign(window, {
  MARKET_STRATEGIES,
  WATCHED_STRATEGIES,
  PUSH_FEED,
  LEADERBOARD_LINES,
  ASSET_FILTERS,
  STYLE_FILTERS,
  DEPLOY_TARGETS,
  seededWalk,
});
